name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck
